### PR TITLE
Spec v2

### PR DESCRIPTION
**Pull request by K-Meech**
fixes https://github.com/mobie/mobie.github.io/issues/51, https://github.com/mobie/mobie.github.io/issues/68 and https://github.com/mobie/mobie.github.io/issues/67

Finally got around to updating mobie.github.io for the new MoBIE version! This is a huge diff, so it's probably easiest to just browse from the index.md for this branch: https://github.com/mobie/mobie.github.io/blob/spec_v2/index.md

@tischi @constantinpape Anything else need adding here?

### CODE REVIEW

**Comment by tischi** [comment]
Thanks a lot!
I would just merge it and then fix bugs.
Looking at the diff is too cumbersome...
OK?

**Comment by constantinpape** [comment]
I will have a quick look at the diff later and then merge @tischi.

**Comment by tischi** [comment]
OK, browsing from the index works 😄 

One issue: 

> Service endpoint - the location of your S3 object store

I would write something that this only applies if using an AWS managed object store. If one uses some other object store, e.g. at EMBL-EBI this should be left blank.

**Comment by tischi** [comment]
Another thing, I would probably make CLI calls be code, e.g.

Instead of

$ aws s3 sync /path/to/my/project https://s3.embl.de/my-bucket

Do this (with the back ticks)
 
`$ aws s3 sync /path/to/my/project https://s3.embl.de/my-bucket`

**Review by constantinpape — COMMENTED** [review]
Thanks @K-Meech! I had a brief look through the diff, but only found a single heading that could be improved. I also agree with @tischi that commands should be markdown rendered via backticks, besides these two minor points this is good to be merged from my side and we can fix more small issues as we find them.

**Comment by K-Meech** [comment]
Good points! I'll make these changes

**Comment by K-Meech** [comment]
> I would write something that this only applies if using an AWS managed object store. If one uses some other object store, e.g. at EMBL-EBI this should be left blank.

@tischi - do you have an example of this? How does the project know where to fetch images from if this is blank?

**Comment by tischi** [comment]
I don't have an example, but here:

https://github.com/mobie/platybrowser-project/blob/8a04f91a32fd2cad013d9d1aa30c105b9bcc1864/data/1.0.1/images/remote/prospr-6dpf-1-whole-ache.xml#L28

This would also work like this:

```
    <ImageLoader format="bdv.n5.s3">
      <Key>0.6.3/images/local/prospr-6dpf-1-whole-ache.n5</Key>
      <SigningRegion></SigningRegion>
      <ServiceEndpoint>https://s3.embl.de</ServiceEndpoint>
      <BucketName>platybrowser</BucketName>
    </ImageLoader>
```

**Comment by K-Meech** [comment]
Ah ok - you mean the signingRegion? Not the serviceEndpoint?

**Comment by K-Meech** [comment]
I make all the fixes in the last commit :)

**Comment by tischi** [comment]
did you bump the patch version?!

**Comment by K-Meech** [comment]
No I didn't. Should I do that now? (it's already merged...)

**Comment by tischi** [comment]
Yes, you could do it directly in develop.

**Comment by K-Meech** [comment]
I take it back - there is a develop branch! I just didn't know it existed haha

**Comment by K-Meech** [comment]
Ah I can't bump the version - because there is no pom in this repo, it's only markdown. If there's anywhere else to change the version, let me know.

**Comment by constantinpape** [comment]
Given that this repo only contains the schema and docs it does not make sense to add a pom. We can instead use github releases (which just map to git tags) to keep track of version changes.

We currently don't have a release yet, but it's easy to create one via the `Create new release` button.
image

But we should define what exactly a release here means, as it makes most sense to use it to keep track of changes in the sepc (as defined by the jsonschema)

**Comment by K-Meech** [comment]
Sounds good to me! I'll make a separate issue for this.

**Pull request merged**
