### PR TITLE
Screenshot tutorial and minor fixes

### PR DESCRIPTION
**Pull request by K-Meech**
Main changes:
- adds screenshot info + show raw images info to ```more_features.md``` . @constantinpape - Would be good to check what I mentioned about the sampling / resolution here, as I wasn't totally sure it was correct.
- Minor fixes to other tutorials, including mentioning the new settings menu in ```explore_a_project.md``` and ```exploring_segmentations.md```. I don't currently show the setting menu for images / regions.

### CODE REVIEW

**Review by constantinpape — APPROVED** [review]

**Comment by constantinpape** [comment]
Thanks @K-Meech !

> * @constantinpape - Would be good to check what I mentioned about the sampling / resolution here, as I wasn't totally sure it was correct.

I will check this in the rendered version and make an issue if something is unclear. (It's probably better if @tischi double checks this since he's most familiar with this; but I will ping again in the issue if necessary).

> * Minor fixes to other tutorials, including mentioning the new settings menu in `explore_a_project.md` and `exploring_segmentations.md`. I don't currently show the setting menu for images / regions.

Sounds good!

**Comment by constantinpape** [comment]
I have merged, but for some reason the commits don't show up on master...
Maybe some temporary issues with github, I will double check tomorrow.

**Comment by constantinpape** [comment]
Ah, nvm you merged into develop...

**Comment by constantinpape** [comment]
@K-Meech: I understand your question now, and I think what you write is correct.
Just to be sure, could you double check this @tischi?

Is the description of sampling here correct:

image

(Decided against opening an issue, since this should be fairly straightforward ;))

**Comment by tischi** [comment]
What exactly is the question? :-)

**Comment by constantinpape** [comment]
Is the description of `Sampling` given here correct?

**Comment by tischi** [comment]
Yes.

**Pull request merged**
